import type { DiagnosticQuestion } from "./types";

export const diagnosticQuestions: DiagnosticQuestion[] = [
  {
    id: "q1",
    skill: "vocabulary",
    prompt: "Что означает مرحباً?",
    options: ["Спасибо", "Привет", "До свидания", "Пожалуйста"],
    answer: "Привет",
    level: "A1",
    points: 10,
  },
  {
    id: "q2",
    skill: "grammar",
    prompt: "Выбери правильное предложение.",
    options: ["أنا طالب", "أنا طلاب", "أنا طالبين", "أنا يطالب"],
    answer: "أنا طالب",
    level: "A1",
    points: 10,
  },
  {
    id: "q3",
    skill: "reading",
    prompt: "Где человек работает?",
    options: ["В школе", "В компании", "В аэропорту", "Дома"],
    answer: "В компании",
    level: "A1",
    points: 10,
  },
  {
    id: "q4",
    skill: "listening",
    prompt: "Выбери перевод شُكْرًا.",
    options: ["Спасибо", "Доброе утро", "Да", "Нет"],
    answer: "Спасибо",
    level: "A1",
    points: 10,
  },
  {
    id: "q5",
    skill: "writing",
    prompt: "Напиши по-арабски: «Меня зовут Анна».",
    type: "text",
    acceptedKeywords: ["اسمي"],
    minWords: 2,
    level: "A1",
    points: 10,
  },
  {
    id: "q6",
    skill: "speaking",
    prompt: "Скажи по-арабски: «Я изучаю арабский язык».",
    type: "text",
    acceptedKeywords: ["أدرس", "العربية"],
    minWords: 2,
    level: "A1",
    points: 10,
  },
];
